[build]
command = "npm run build"
publish = "build"
environment = { NODE_VERSION = "14.17.0" }

[[plugins]]
package = "netlify-plugin-inline-cache"
[plugins.inputs]
paths = ["node_modules", ".cache", "build"]
