[build]
command = "npm run build"
publish = "build"
environment = { NODE_VERSION = "14.17.0" }

[context.production]
command = "npm run build"

[[plugins]]
package = "@netlify/plugin-cache"
config = { cache = ["node_modules", ".cache", "build"] }
